#!/usr/bin/env python3
"""
verify_schema_drift.py  —  W0.0  فحص انحراف المخطط (Schema Drift Guard)

المرجع الوحيد المعتمد:  json_output.txt  (لقطة حيّة من Supabase)
يقارنه بـ:
    supabase/schema_production.sql
    supabase/init.sql
    supabase/migrations/*.sql

Static analysis بلا اتصال بقاعدة البيانات ⇒ يعمل في CI بلا أسرار.

الاستخدام:
    python supabase/tools/verify_schema_drift.py
    python supabase/tools/verify_schema_drift.py --json
خروج غير صفري (1) عند وجود انحراف ⇒ يمنع النشر.
"""
import argparse
import json
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
JSON_REF = os.path.join(ROOT, "json_output.txt")
SCHEMA_PROD = os.path.join(ROOT, "supabase", "schema_production.sql")
INIT_SQL = os.path.join(ROOT, "supabase", "init.sql")
MIGRATIONS = os.path.join(ROOT, "supabase", "migrations")

GREEN, RED, YELLOW, CYAN, DIM, RESET = (
    "\033[32m", "\033[31m", "\033[33m", "\033[36m", "\033[2m", "\033[0m")


def load_reference(path):
    """يحلّل json_output.txt → جداول/أعمدة + سياسات + تريiggers + دوال."""
    ref = {"tables": defaultdict(set), "policies": set(), "triggers": set(),
           "functions": set(), "constraints": set(), "buckets": set()}
    if not os.path.exists(path):
        sys.exit(f"ABORT: المرجع غير موجود: {path}")
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            # كل سطر في json_output.txt صفّ جدول Markdown:
            #   | {"type":...}   |   |   ⇒ JSON بين أول | وآخر | في السطر
            m = re.search(r"\|\s*(\{.*?\})\s*(?:\||\s*$)", line)
            if not m:
                continue
            try:
                o = json.loads(m.group(1))
            except json.JSONDecodeError:
                continue
            t = o.get("type")
            if t == "Table":
                ref["tables"][o["table_name"]].add(
                    (o["column_name"], o.get("data_type", "")))
            elif t == "RLS Policy":
                ref["policies"].add(o["policy_name"])
            elif t == "Trigger":
                # RI_ConstraintTrigger_* are auto-generated by PostgreSQL for
                # every FOREIGN KEY. They are database internals, never hand-
                # written, so they are noise here and must not count as drift.
                name = o["trigger_name"]
                if not name.startswith("RI_ConstraintTrigger"):
                    ref["triggers"].add(name)
            elif t == "Function":
                ref["functions"].add(o["routine_name"])
            elif t == "Constraint":
                ref["constraints"].add(o.get("constraint_name", ""))
            elif t == "Bucket":
                ref["buckets"].add(o.get("bucket_name", o.get("name", "")))
    return ref


def tables_in_sql_file(path):
    """أسماء الجداول المُعرَّفة فعلياً (CREATE TABLE فقط، لا ALTER)."""
    if not os.path.exists(path):
        return set()
    names = set()
    pat = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?(\w+)",
        re.IGNORECASE)
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = pat.search(line)
            if m:
                names.add(m.group(1))
    return names


def objects_in_sql_dir(path):
    """يجمع الدوال/السياسات/التريiggers المعرّفة في مجلد migrations."""
    fn, pol, trg = set(), set(), set()
    if not os.path.isdir(path):
        return fn, pol, trg
    pats = {
        "fn": re.compile(
            r"CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+(?:public\.)?(\w+)",
            re.IGNORECASE),
        "pol": re.compile(r"CREATE\s+POLICY\s+(\w+)", re.IGNORECASE),
        "trg": re.compile(r"CREATE\s+TRIGGER\s+(\w+)", re.IGNORECASE),
    }
    for root, _dirs, files in os.walk(path):
        for f in files:
            if not f.endswith(".sql"):
                continue
            with open(os.path.join(root, f), encoding="utf-8",
                      errors="replace") as fh:
                for line in fh:
                    for key, pat in pats.items():
                        m = pat.search(line)
                        if m:
                            {"fn": fn, "pol": pol, "trg": trg}[key].add(m.group(1))
    return fn, pol, trg
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true", help="JSON output for CI")
    args = ap.parse_args()

    ref = load_reference(JSON_REF)
    ref_tables = set(ref["tables"])
    prod_tables = tables_in_sql_file(SCHEMA_PROD)
    init_tables = tables_in_sql_file(INIT_SQL)
    mig_fn, mig_pol, mig_trg = objects_in_sql_dir(MIGRATIONS)

    missing_prod = sorted(ref_tables - prod_tables)
    extra_prod = sorted(prod_tables - ref_tables)
    missing_init = sorted(ref_tables - init_tables)
    missing_trg = sorted(ref["triggers"] - mig_trg)

    init_txt = ""
    if os.path.exists(INIT_SQL):
        with open(INIT_SQL, encoding="utf-8", errors="replace") as fh:
            init_txt = fh.read()
    missing_fn = sorted(
        f for f in ref["functions"]
        if f not in mig_fn and f"FUNCTION public.{f}" not in init_txt
        and f"FUNCTION {f}" not in init_txt)

    junk = sorted(f for f in os.listdir(MIGRATIONS)
                  if re.search(r"\.(bak|orig)", f)
                  or ".bak_" in f or ".orig_" in f)

    report = {
        "reference": {"tables": len(ref_tables),
                      "policies": len(ref["policies"]),
                      "triggers": len(ref["triggers"]),
                      "functions": len(ref["functions"]),
                      "buckets": sorted(ref["buckets"])},
        "missing_in_schema_production": missing_prod,
        "extra_in_schema_production": extra_prod,
        "not_defined_in_init_sql": missing_init,
        "missing_triggers_in_migrations": missing_trg,
        "missing_functions_in_migrations": missing_fn,
        "backup_files_in_migrations": junk,
    }
    drift = bool(missing_prod or extra_prod or missing_trg or missing_fn or junk)

    if args.json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return 1 if drift else 0

    R = report["reference"]
    W = 78
    print("=" * W)
    print("  W0.0  VERIFY SCHEMA DRIFT  --  ref: json_output.txt")
    print("=" * W)
    print(f"{DIM}production: {R['tables']} tables / {R['policies']} policies / "
          f"{R['triggers']} triggers / {R['functions']} functions / "
          f"buckets: {', '.join(R['buckets']) or '-'}{RESET}")
    print(f"{DIM}schema_production.sql: {len(prod_tables)} tables | "
          f"init.sql: {len(init_tables)} tables | migrations/: "
          f"{len(mig_fn)} fn / {len(mig_pol)} policies / {len(mig_trg)} trg{RESET}")
    print("-" * W)

    def section(title, items, note=""):
        icon = f"{RED}x DRIFT{RESET}" if items else f"{GREEN}v OK{RESET}"
        print(f"\n  {icon}  {title}")
        if note:
            print(f"        {DIM}{note}{RESET}")
        for i in items:
            print(f"        {YELLOW}* {i}{RESET}")
        if not items:
            print(f"        {DIM}(none){RESET}")

    section("1a. tables in production MISSING from schema_production.sql",
            missing_prod, "=> db push from that file breaks sync")
    section("1b. tables in schema_production.sql NOT in production",
            extra_prod, "=> file declares phantom tables")
    print(f"\n  {DIM}note: init.sql omits {len(missing_init)} tables by design "
          f"(migrations build on it) - not drift.{RESET}")
    section("2. triggers in production NOT defined in migrations/",
            missing_trg, "=> re-deploy silently drops them")
    section("3. functions in production NOT defined in migrations/init.sql",
            missing_fn)
    section("4. backup files (.bak/.orig) inside migrations/",
            junk, "=> pollutes db reset and git grep")

    print("\n" + "=" * W)
    if drift:
        print(f"  {RED}{YELLOW}RESULT: DRIFT DETECTED{RESET} - do not deploy")
        print(f"  {DIM}action: W0.2 (complete schema_production) / "
              f"W0.3 (move .bak files){RESET}")
    else:
        print(f"  {GREEN}v no drift detected{RESET}")
    print("=" * W)
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())